"""Global Inventory Table"""
create table
  public.global_inventory (
    id bigint generated by default as identity,
    gold integer null,
    red_ml integer null,
    green_ml integer null,
    blue_ml integer null,
    dark_ml integer null,
    constraint global_inventory_pkey primary key (id)
  ) tablespace pg_default;


"""Potion Inventory Table"""
create table
  public.potion_inventory (
    id bigint generated by default as identity,
    sku text not null,
    quantity integer not null,
    price integer not null,
    potion_type integer[] not null,
    name text not null,
    constraint potion_inventory_pkey primary key (id),
    constraint potion_inventory_name_key unique (name),
    constraint potion_inventory_potion_type_key unique (potion_type),
    constraint potion_inventory_sku_key unique (sku),
    constraint potion_inventory_price_check check ((price >= 0)),
    constraint potion_inventory_quantity_check check ((quantity >= 0))
  ) tablespace pg_default;


"""Carts Table"""
create table
  public.carts (
    id bigint generated by default as identity,
    created_at timestamp with time zone null default now(),
    customer text null,
    constraint carts_pkey primary key (id),
    constraint carts_id_key unique (id)
  ) tablespace pg_default;


"""Cart Items Table"""
create table
  public.cart_items (
    id bigint generated by default as identity,
    created_at timestamp with time zone null default now(),
    cart_id bigint not null,
    potion_id bigint not null,
    quantity integer not null,
    constraint cart_items_pkey primary key (id),
    constraint cart_items_cart_id_fkey foreign key (cart_id) references carts (id),
    constraint cart_items_potion_id_fkey foreign key (potion_id) references potion_inventory (id),
    constraint cart_items_quantity_check check ((quantity >= 0))
  ) tablespace pg_default;